### ISSUE TITLE
Error thrown when using SQL Server Named Instances 

### ISSUE THREAD

**Issue by yorek** [SolidQIT/ABI-Solution#3]
When the connection string points to a SQL Server Named Instance the plugin cannot connect to SQL Server

**Comment by EiFilip** [comment]
I have submitted a fix/workaround as a new pull request in the ABI-Compiler solution. I wrote more info about it in the description there.

**Comment by yorek** [comment]
Fixed upgrading compiler to version v3.2.1.3 with commit  6081df1a0063f6124bf9c9466d0a512960406e5b
